spring:
  application:
    name: store-api
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Zxc0987654321.
  jpa:
    show-sql: true